# Generated by Django 6.0.3 on 2026-03-28 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('relevant', 'Relevant'), ('irrelevant', 'Irrelevant')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('content_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='monitoring.contentitem')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='monitoring.keyword')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('keyword', 'content_item'), name='unique_flag')],
            },
        ),
    ]
